[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server configuration-driven ModelContextProtocol (MCP) server designed for ComfyUI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
]
